name: maze_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dartx: ^1.2.0

  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.9

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
